#theme: jekyll-theme-minimal
remote_theme: eliottvincent/bay

header:
  pages:
    - name: About
      slug: /
    - name: Projects
      slug: /projects
      link: projects.md
    - name: Interests
      slug: /interests
      link: interests.md
    
footer:
  show_powered_by: false
  contact:
    - name: Email
      value: charleneostang@yahoo.com
      link: mailto:charleneostang@yahoo.com
    - name: WeChat
      value: Calendly
      link: https://calendly.com/charleneostang/30min
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/charleneostang
