theme: jekyll-theme-minimal
#remote_theme: charleneostang/bay

site:
  title: Charlene Tang
  
header:
  pages:
    - name: About
      slug: /
    - name: Projects
      slug: /projects
      link: projects.md
    - name: Interests
      slug: /interests
      link: interests.md
    
footer:
  show_powered_by: true
  contact:
    - name: Email
      value: charleneostang@yahoo.com
      link: mailto:charleneostang@yahoo.com
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/charleneostang
