#theme: jekyll-theme-minimal
remote_theme: eliottvincent/bay

header:
  pages:
    - name: About
      slug: /
    - name: Projects  
    - name: Interests  
    
footer:
  show_powered_by: true
  contact:
    - name: Email
      value: charleneostang@yahoo.com
      link: mailto:charleneostang@yahoo.com
    - name: Phone
      value: Calendly
      link: https://calendly.com/charleneostang/30min
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/charleneostang
